/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author swathi
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;




public class frame7 extends javax.swing.JFrame {

    /**
     * Creates new form frame7
     */
    String s;
    String q;
    int c=1;
    public frame7() {
        initComponents();
    }
    public frame7(String a,String b)
    {
        s=a;
        q=b;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 418));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jLabel1.setText("Enter amount to be transferred");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 80, 320, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(391, 83, 107, 28);

        jLabel2.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jLabel2.setText("Enter the account no");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 152, 320, 26);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(391, 223, 107, 28);

        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(250, 300, 100, 30);

        jLabel3.setFont(new java.awt.Font("Waree", 0, 15)); // NOI18N
        jLabel3.setText("Enter account no to transfer");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 220, 320, 30);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(391, 150, 107, 28);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel4.setText("Money Transfer");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(190, 20, 210, 29);

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(400, 340, 70, 30);

        jButton3.setBackground(new java.awt.Color(255, 128, 0));
        jButton3.setIcon(new javax.swing.ImageIcon("/home/swathi/Downloads/icons8-login-50.png")); // NOI18N
        jButton3.setText("Logout");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(480, 0, 160, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon("/home/swathi/Downloads/Blooker20.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 830, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {                                         
            // TODO add your handling code here:
            Connection conn;
            String sq="";
            String sql="";
            String sq1=" ";
            Connect ob=new Connect();
            conn=ob.getConnection();
            int x=Integer.parseInt(jTextField1.getText());
            int y;
            y = Integer.parseInt(jTextField2.getText());
            int z;
            z = Integer.parseInt(jTextField3.getText());
            if(s.equals("Savings"))
            {
                sq1="Update current Set balance= balance+?  where accountno=?";
                sql="Update savings Set balance= balance+? where accountno=?";
                sq="Update savings Set balance= balance-? where accountno=?";
                
            }
            
            
            
            
            else if(s.equals("Current"))
            {
                sq1="Update savings Set balance= balance+?  where accountno=?";
                sql="Update current Set balance= balance+? where accountno=?";
                sq="Update current Set balance= balance-? where accountno=?";
                
                
                
            }
            String sq2="Update user Set balance= balance+? where cardnumber=?";
            String sq3="Update user Set balance= balance-? where cardnumber=?";
            PreparedStatement pst,ps1,ps2,ps3;
            
            try {
                ps2=conn.prepareStatement(sq2);
                ps2.setInt(1,x);
                ps2.setString(2, String.valueOf(y));
                
                ps3=conn.prepareStatement(sq3);
                ps3.setInt(1,x);
                ps3.setString(2, String.valueOf(z));
                
                ps1=conn.prepareStatement(sq1);
                ps1.setInt(1,x);
                ps1.setString(2, String.valueOf(y));
                
                pst = conn.prepareStatement(sql);
                pst.setInt(1,x);
                pst.setString(2, String.valueOf(y));
                
                PreparedStatement ps=conn.prepareStatement(sq);
                ps.setInt(1,x);
                ps.setString(2, String.valueOf(z));
                int rs1;
                rs1 = pst.executeUpdate();
                int rs2;
                rs2 = ps.executeUpdate();
                int res= ps1.executeUpdate();
                int res1;
                res1 = ps2.executeUpdate();
                int res2=ps3.executeUpdate();
                if(rs2>0)
                {
                    if(res>0||rs1>0)
                    {
                        JOptionPane.showMessageDialog(null,"Amount successfully transferred");
                    }
                }
                
                
            }
            
            catch (SQLException ex) {
                Logger.getLogger(frame7.class.getName()).log(Level.SEVERE, null, ex);
            }
            PreparedStatement p1,p2;
            java.util.Date  d=new java.util.Date();
            java.sql.Date d1=new java.sql.Date(d.getTime());
            java.sql.Time t=new java.sql.Time(d.getTime());
            String sq5="Insert into transact(slno,date,time,type,accountno,amount)values(?,?,?,?,?,?)";
            
            p1=conn.prepareStatement(sq5);
            p1.setInt(1,c);
            c++;
            p1.setInt(5,z);
            p1.setInt(6,x);
            p1.setString(4,"Transfer");
            p1.setDate(2,d1);
            p1.setTime(3,t);
            p2=conn.prepareStatement(sq5);
            p2.setInt(1,c);
            c++;
            p2.setInt(5,y);
            p2.setInt(6,x);
            p2.setString(4,"Deposit");
            p2.setDate(2,d1);
            p2.setTime(3,t);
            p1.executeUpdate();
            p2.executeUpdate();
            
            
            
            
            
            
            
            
            
            
            
            
        } 
        
        catch (SQLException ex) {
            Logger.getLogger(frame7.class.getName()).log(Level.SEVERE, null, ex);
        }  
       
       
        
        
          
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        frame4 ob=new frame4(s,q);
        ob.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        frame2 f=new frame2();
        f.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
