
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author swathi
 */
public class frame3 extends javax.swing.JFrame {

    /**
     * Creates new form frame3
     */
    String s;
    public frame3() {
        initComponents();
    }
    public frame3(String s)
            
    {
        this.s=s;
      initComponents();
      Connection con;
      Connect ob1=new Connect();
      con=ob1.getConnection();
      
      String sq="Select * from user where name=?";
        try {
            PreparedStatement pst=con.prepareStatement(sq);
            jLabel3.setText(s);
            pst.setString(1,jLabel3.getText());
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                
                if(rs.getString("accounttype").equals(jLabel12.getText()))
                {
                    jLabel14.setText(rs.getString("cardnumber"));
                    jLabel16.setText(rs.getString("balance"));
                    
                }
                else if(rs.getString("accounttype").equals(jLabel11.getText()))
                {
                    jLabel13.setText(rs.getString("cardnumber"));
                    jLabel15.setText(rs.getString("balance"));
                    
                } 
               
                      
            }
        } catch (SQLException ex) {
            Logger.getLogger(frame3.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(771, 326));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("URW Palladio L", 1, 24)); // NOI18N
        jLabel1.setText("Choose your account type");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(210, 10, 310, 30);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        jLabel4.setText("Type");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(99, 72, 34, 19);

        jLabel5.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        jLabel5.setText("Card Number");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(264, 72, 102, 19);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 3, 16)); // NOI18N
        jLabel6.setText("Balance");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(460, 70, 62, 19);

        jButton1.setText("Select");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(612, 132, 90, 30);

        jLabel11.setText("Savings");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(95, 144, 51, 18);

        jLabel13.setText("-");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(264, 144, 102, 18);

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(612, 180, 90, 30);

        jLabel12.setText("Current");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(95, 192, 55, 18);

        jLabel14.setText("-");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(264, 192, 102, 18);

        jLabel15.setText("-");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(492, 144, 102, 18);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 100, 40);

        jLabel16.setText("-");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(492, 192, 102, 18);

        jButton3.setBackground(new java.awt.Color(255, 128, 0));
        jButton3.setForeground(new java.awt.Color(38, 30, 23));
        jButton3.setIcon(new javax.swing.ImageIcon("/home/swathi/Downloads/icons8-login-50.png")); // NOI18N
        jButton3.setText("Logout");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(630, 0, 140, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon("/home/swathi/Downloads/Blooker20.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, 0, 790, 330);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jLabel14.getText().equals("-"))
        {
            JOptionPane.showMessageDialog(null,"Account doesnt exist");
        }
         else
        {setVisible(false);
        frame4 ob=new frame4("Current",s);
        ob.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jLabel13.getText().equals("-"))
        {
            JOptionPane.showMessageDialog(null, "Account doesnt exist");
        }
        else
        {
            setVisible(false);
        frame4 ob=new frame4("Savings",s);
        ob.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        frame2 f=new frame2();
        f.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
